FROM python:3.12.8-slim

WORKDIR /app

# Now we can copy from the entire repo structure
COPY DefectScore/ /app/DefectScore/
# etc., if you want more

WORKDIR /app/DefectScore
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]