services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  afferent-api:
    build:
      context: ./AfferentCoupling
    container_name: afferent-api-container
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/afferent_db
    depends_on:
      - mongodb
  
  defectdensityapi:
    build:
      context: ./DefectDensity-API
    container_name: defectdensityapi
    ports:
      - "8083:8083"
    environment:
      # Point URI at 'mongodb', because that's the service name
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/defectdensitydb
    depends_on:
      - mongodb

volumes:
  mongo_data:
