services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  afferent-api:
    build:
      context: .
      dockerfile: AfferentCoupling/Dockerfile
    container_name: afferent-api-container
    ports:
      - "8081:8081"
    volumes:
      - shared-repos:/shared/repos

  efferent-api:
    build:
      context: .
      dockerfile: EfferentCoupling-API/Dockerfile
      args:
        SERVICE_NAME: efferent
    container_name: efferent-api-container
    ports:
      - "8082:8082"
    volumes:
      - shared-repos:/shared/repos

  defectdensity-api:
    build:
      context: ./DefectDensity-API
    container_name: defectdensityapi
    ports:
      - "8083:8083"

  lcom4:
    build:
      context: .
      dockerfile: ./LCOM4/dockerfile
    container_name: lcom4_container
    # depends_on:
    #   - mongodb
    ports:
      - "8001:8000" # host:container
    # environment:
    #   - MONGO_URI=mongodb://mongodb:27017/
    volumes:
      - shared-repos:/shared/repos
    # If you only want the gateway to call it internally, you can omit the port mapping.
    # But let's keep it to show direct access for debugging.

  lcomhs:
    build:
      context: .
      dockerfile: ./LCOMHS/dockerfile
    container_name: lcomhs_container
    # depends_on:
    #   - mongodb
    ports:
      - "8002:8000" # host:container
    # environment:
    #   - MONGO_URI=mongodb://mongodb:27017/
    volumes:
      - shared-repos:/shared/repos
    # If you only want the gateway to call it internally, you can omit the port mapping.
    # But let's keep it to show direct access for debugging.

  defectscore:
    build:
      context: ./DefectScore
      dockerfile: dockerfile
    container_name: defect_score_container
    depends_on:
      - mongodb
    ports:
      - "8003:8000" # host:container
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    # If you only want the gateway to call it internally, you can omit the port mapping.
    # But let's keep it to show direct access for debugging.

  benchmark:
    build:
      context: ./Benchmark
      dockerfile: dockerfile
    container_name: benchmark_container
    ports:
      - "8004:8000" # host:container
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

  instability:
    build:
      context: ./Instability
      dockerfile: dockerfile
    container_name: instability_container
    ports:
      - "8005:8000" # host:container
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

  gateway:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    container_name: gateway_container
    ports:
      - "8080:8080" # host:gateway
    environment:
      - LCOM4_SERVICE_URL=http://lcom4:8000
      - LCOMHS_SERVICE_URL=http://lcomhs:8000
      - DEFECT_SCORE_SERVICE_URL=http://defectscore:8000
      - BENCHMARK_SERVICE_URL=http://benchmark:8000
      - INSTABILITY_SERVICE_URL=http://instability:8000
      - AFFERENT_SERVICE_URL=http://afferent-api:8081
      - EFFERENT_SERVICE_URL=http://efferent-api:8082
      - DEFECTDENSITY_SERVICE_URL=http://defectdensity-api:8083
    depends_on:
      - lcom4
      - lcomhs
      - defectscore
      - benchmark
      - instability
      - afferent-api
      - efferent-api
      - defectdensity-api

volumes:
  mongo_data:
  shared-repos:
