FROM python:3.12.8-slim

# Set base working directory
WORKDIR /app

# Copy LCOM4 source code
COPY LCOM4/ /app/LCOM4/

# Copy shared utilities folder
COPY utilities/ /app/utilities/

# Install system dependencies
RUN apt-get update && apt-get install -y git && apt-get clean

WORKDIR /app/LCOM4
# Install Python dependencies
# Assumes requirements.txt is inside LCOM4/
RUN pip install --no-cache-dir -r requirements.txt

# Set PYTHONPATH to include /app so that `from utilities...` works
ENV PYTHONPATH="/app"

# Set working directory to where your main.py lives

EXPOSE 5000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
