name: CI/CD - Software Quality Metrics Backend Services

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-java-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Afferent Coupling API
      - name: Build Afferent Coupling API
        run: mvn install -DskipTests --file AfferentCoupling/pom.xml

      - name: Test Afferent Coupling API
        run: mvn test --file AfferentCoupling/pom.xml

      - name: Dockerize Afferent Coupling API
        run: docker build -t afferent-api AfferentCoupling/

      # Efferent Coupling API
      - name: Build Efferent Coupling API
        run: mvn install -DskipTests --file EfferentCoupling-API/pom.xml

      - name: Test Efferent Coupling API
        run: mvn test --file EfferentCoupling-API/pom.xml

      - name: Dockerize Efferent Coupling API
        run: docker build -t efferent-api EfferentCoupling-API/

      # Defect Density API
      - name: Build Defect Density API
        run: mvn install -DskipTests --file DefectDensity-API/pom.xml

      - name: Test Defect Density API
        run: mvn test --file DefectDensity-API/pom.xml

      - name: Dockerize Defect Density API
        run: docker build -t defectdensity-api DefectDensity-API/

  build-python-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Defect Score
      - name: Install DefectScore dependencies
        run: pip install -r DefectScore/requirements.txt

      - name: Test DefectScore
        run: pytest DefectScore/tests

      - name: Dockerize DefectScore
        run: docker build -t defect-score DefectScore/

      # LCOM4
      - name: Install LCOM4 dependencies
        run: pip install -r LCOM4/requirements.txt

      - name: Test LCOM4
        run: pytest LCOM4/tests

      - name: Dockerize LCOM4
        run: docker build -t lcom4 LCOM4/

      # LCOMHS
      - name: Install LCOMHS dependencies
        run: pip install -r LCOMHS/requirements.txt

      - name: Test LCOMHS
        run: pytest LCOMHS/tests

      - name: Dockerize LCOMHS
        run: docker build -t lcomhs LCOMHS/

      # Middleware
      - name: Install Middleware dependencies
        run: pip install -r middleware/requirements.txt

      - name: Test Middleware
        run: pytest middleware/tests

      - name: Dockerize Middleware
        run: docker build -t middleware middleware/