name: CI/CD - Software Quality Metrics Backend Services

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-java-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Afferent Coupling API
      - name: Build with Maven
        run: mvn clean package --file AfferentCoupling/pom.xml

      - name: Run Unit Tests
        run: mvn test --file AfferentCoupling/pom.xml

      - name: Build Docker image
        run: docker build -t afferent-api AfferentCoupling/
